export default {
    SET_CHANNEL_INFO: 'SET_CHANNEL_INFO',
    SET_VIDEO_LIST: 'SET_VIDEO_LIST',
    SET_SET_LIST: 'SET_SET_LIST',
    SET_PAGE_NUM: 'SET_PAGE_NUM',
    SET_SID: 'SET_SID',
    SET_ACTIVE_SID: 'SET_ACTIVE_SID',
    SET_LOADING_STATE: 'SET_LOADING_STATE',
    SET_COMPLETE_STATE: 'SET_COMPLETE_STATE',
    SET_SHOW_STATE: 'SET_SHOW_STATE',
    SET_USER_ID: 'SET_USER_ID',
    SET_ORIGIN: 'SET_ORIGIN',

    GET_CHANNEL_INFO: 'GET_CHANNEL_INFO',
    GET_SET_LIST: 'GET_SET_LIST',
    GET_VIDEO_lIST: 'GET_VIDEO_lIST'

}